package com.example.provider;

import org.osgi.service.component.annotations.Component;

@Component(service = GreetingService.class, immediate = true)
public class GreetingServiceImpl implements GreetingService {
    @Override
    public String sayHello(String name) {
        return "Hello " + name + ", this message was generated by the Provider Bundle!";
    }
}